### ISSUE TITLE
#10 通信で送るデータ型の変更

### ISSUE THREAD

**Issue by Y-Wakuta** [AlbatrossAvionics/Alba-2017#10]
- [x] 全ての通信に適用する。
- [x] 2016年度は通信は全てcharで送信していたが、doubleの値をcharに変換する際に256以上の値と小数点以下の値は切られていたので、doubleの値をそのままcharに変換すう（char型の配列に格納する）関数を作成する。

**Comment by Tsumagari** [comment]
mbed.hで使えるsprintf(char *, "%f", float/double);でchar型配列にfloatやdouble型の変数を書式付きで代入できることが分かりました。

**Comment by Tsumagari** [comment]
char配列のポインタを他の方のポインタ型にキャストしてから代入する方法が使えるようです。
参考：[http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q14129868014](http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q14129868014)
テストコード：[https://developer.mbed.org/users/tsumagari/code/test_cast/](https://developer.mbed.org/users/tsumagari/code/test_cast/)
