### ISSUE TITLE
#14 操縦桿のジョイスティックの動作確認を行う

### ISSUE THREAD

**Issue by Y-Wakuta** [AlbatrossAvionics/Alba-2017#14]
- [x] ジョイスティックを用意
  * 一つ一軸ずつ操舵に使用する。
  * ばねで中央に戻るもの
  * 重さ40g程度

**Comment by Tsumagari** [comment]
操舵ボードにジョイスティックをロール操作用・ピッチ操作用の2つ追加しました。
また読んだアナログ値を平均化する関数を作成し操舵ボードに追加しました。
翼内CAN通信で操舵から送るデータ数を2バイト→5バイトに増やし、はじめの4バイトにエルロン操舵用のfloat値を割り当てました。角度の調整はまだ必要ですが、動きます。
