### ISSUE TITLE
#2 回転数計の実装

### ISSUE THREAD

**Issue by AlbaAvionics** [AlbatrossAvionics/Alba-2017#2]
- [x] 電池ボックスを取り付け、モジュールを完成させる。
- [x] 自転車のクランクに取り付けた後、サイクルコンピュータと比較して校正を行う。
- [x] 機体データ送信用のTweLiteと干渉しないようにグループ分けを行う。
- [x] 基板の裏をスプレーで絶縁する。
- [x] 2017年度ソースコードへの追加

**Comment by Tsumagari** [comment]
校正：ジャイロセンサがデフォルトの250dpsのままだからか、z軸周りの角速度286rad/s（回転数47.6r/m）以上の値が取れませんでした。twelite SDKでアプリを書き換えて2000dpsのモードに変えてからもう一度検証したいです

**Comment by Tsumagari** [comment]
校正：書き換え版アプリを入れて2000dpsモードでもう一度検証。ケイデンス1~2r/m程度の誤差は出ますがほぼ線形なデータがとれました。生のデータで実装する予定です。
基盤：電源スイッチを追加したいです。電池ボックスも基盤に固定したいです

**Comment by Y-Wakuta** [comment]
基板への電池ボックス固定確認しました。すごくいいと思います。

ところで、使用しているTweLiteの機体データ送信用の物との干渉を防ぐためのグループ分けは現状どんな感じですか？

**Comment by Tsumagari** [comment]
まだどちらもデフォルトの周波数のままなのでグループ分けはされてないです。
