### ISSUE TITLE
TFまでのTODO

### ISSUE THREAD

**Issue by Tsumagari** [AlbatrossAvionics/Alba-2017#29]
-  [x] ジョイスティックの範囲
 -  [x] ケイデンス受信tweliteのケーブル
 -  [ ] ケイデンス送信側の電源が切れたときに処理から抜ける
 -  [x] マジックテープ買い出し
 -  [x] ロールアラーム鳴らす＆ケーブル
 -  [ ] 翼端mpu(最悪1stTFでは妥協)

**Comment by Y-Wakuta** [comment]
ジョイスティックの範囲に関しては、メイン側で段階を表すためにintで送る仕様に変更
