### ISSUE TITLE
 #4 桁試験用の作成高度計セット

### ISSUE THREAD

**Issue by AlbaAvionics** [AlbatrossAvionics/Alba-2017#4]
- [x] センサモデュールの作成
- [x] 2017年度ソースコードへの組み込み

- 距離センサ+mbed(Arduino)+Twe-Liteのモジュールを一つ作る。
- 高度計の校正に2日、その他の作成に1日で仕上げたい。

**Comment by Tsumagari** [comment]
基盤を作り、校正まで完了しました。誤差１ｃｍ未満です！
[https://developer.mbed.org/teams/albatross/code/sonar_test/](https://developer.mbed.org/teams/albatross/code/sonar_test/)
ただしセンサーは一番早く帰ってきた音波で距離を測るので、測りたい距離が長くなるほど放射される超音波が当たる範囲が広がって周りの障害物の影響を受けやすくなります。
また機体への実装へ向けて、センサーが動くとき・風が強いときの計測値への影響も確認したいです。

**Comment by Y-Wakuta** [comment]
ごめん、報告会とかでバタバタしてて、確認できてませんでした。素晴らしいね。じゃあ、桁試験の分の準備は終了してるんかな？

**Comment by Tsumagari** [comment]
電圧をアナログで読む方式で2017年度のソースコードに実装できました。まだちゃんとした校正はできていませんがざっくりテストしたところ誤差2cmくらいで読めていそうです。
