### ISSUE TITLE
風速計の調整

### ISSUE THREAD

**Issue by Y-Wakuta** [AlbatrossAvionics/Alba-2017#42]
今年買ったセンサで実装しなおせないか再度挑戦

**Comment by Tsumagari** [comment]
and回路を使用してパルス数をカットする方法は、ロータリーエンコーダーがhighの状態で停止したときに誤パルスが入力されてしまいました。
また計器mbed内でピン割込みを一定時間だけ有効にする方法では、タイマー割込みが増えた影響か、操舵mbedからの受信データが乱れました。

**Comment by Y-Wakuta** [comment]
他のTODOがたくさんある（他班の手伝いも含めて）のでいったんclose
