### ISSUE TITLE
#8 リセットスイッチを実装

### ISSUE THREAD

**Issue by AlbaAvionics** [AlbatrossAvionics/Alba-2017#8]
- [x] テスト
- [x] 2017年度ソースコードへの追加

* 昨年度リセットスイッチがなかったため、リセットをパイロットが行うことができず、効率が悪かった。
* mbedのリセットピンを使用する。
* リセットをした際に、他のandroidなどと、データを同期しなおさなければならない。

**Comment by Tsumagari** [comment]
mbed_reset関数を使ってボタン長押しでリセットできるようなプログラムを作りました。
[https://developer.mbed.org/users/tsumagari/code/mbed_reset_test/](https://developer.mbed.org/users/tsumagari/code/mbed_reset_test/)

**Comment by Y-Wakuta** [comment]
プルダウン抵抗をつける。
ちなみにここでプロアップ抵抗側にするのは絶対にダメ

**Comment by Tsumagari** [comment]
プルダウン抵抗付のリセットボタン基盤を作成しました。
