### ISSUE TITLE
#9 SoftwareSerialのテスト

### ISSUE THREAD

**Issue by Y-Wakuta** [AlbatrossAvionics/Alba-2017#9]
* 今年度は通信数が増えるため、既存のシリアルピンだけでは足りない。そこで、ソフトウェアシリアルでシリアルポートの増設を試みる。
* 普通にソフトウェアシリアルのライブラリを動かないらしいのでこのURLのページをしっかり参照すること。
[参考ページ](http://blog.goo.ne.jp/roboz80/e/0c9a6f6209a0e36a6dc35092fc429fca)

**Comment by Tsumagari** [comment]
上記HP上の通りライブラリを直してテストしたところ、putc関数getc関数ともに問題なく使えます。ただreadableはシリアルが未接続の場合1が返るので少し気を付けてください。

**Comment by Tsumagari** [comment]
mbedのTickerで割り込み指定した関数内で、forでputcを繰り返すとmbedがフリーズするようです。mainのwhileループ内でならforで繰り返しても（waitをかませれば）使えます。
ソフトウェアシリアルで2016年度のmbed間シリアル通信を肩代わりさせると、本家シリアルを使った時より送られてくるデータの精度が悪いです。。

**Comment by Tsumagari** [comment]
新しいライブラリを見つけました！[https://developer.mbed.org/users/Sissors/code/BufferedSoftSerial/](https://developer.mbed.org/users/Sissors/code/BufferedSoftSerial/)
割り込み内でも使え、さらにtwe-liteともボーレート9600,19200の設定であれば使えるようです。（38400以上のレートでは文字化けが起こります。）昨年度のシステムのmbed間SerialをBufferedSoftSerialに置き換えて動作確認もできました。コードはパブリッシュ済みです。
